//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompanyInThePocket.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCompanyInThePocket.Core.Resources.StringValues", typeof(StringValues).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACRA.
        /// </summary>
        public static string Main_Meetings_Title_Text {
            get {
                return ResourceManager.GetString("Main_Meetings_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoir l&apos;intro.
        /// </summary>
        public static string Main_Settings_Intro {
            get {
                return ResourceManager.GetString("Main_Settings_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se déconnecter.
        /// </summary>
        public static string Main_Settings_Logout {
            get {
                return ResourceManager.GetString("Main_Settings_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préférences.
        /// </summary>
        public static string Main_Settings_Title_Text {
            get {
                return ResourceManager.GetString("Main_Settings_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liens utiles.
        /// </summary>
        public static string Main_UseFullLinks_Title_Text {
            get {
                return ResourceManager.GetString("Main_UseFullLinks_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avant vente.
        /// </summary>
        public static string MeetingType_AvantVente {
            get {
                return ResourceManager.GetString("MeetingType_AvantVente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conférence.
        /// </summary>
        public static string MeetingType_Conference {
            get {
                return ResourceManager.GetString("MeetingType_Conference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congé.
        /// </summary>
        public static string MeetingType_CP_RTT {
            get {
                return ResourceManager.GetString("MeetingType_CP_RTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string MeetingType_Mission {
            get {
                return ResourceManager.GetString("MeetingType_Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non facturé.
        /// </summary>
        public static string MeetingType_NonFacture {
            get {
                return ResourceManager.GetString("MeetingType_NonFacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer vers l&apos;application.
        /// </summary>
        public static string Startup_ConnectionButton_Text {
            get {
                return ResourceManager.GetString("Startup_ConnectionButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus besoin de chercher,
        ///tout est ici....
        /// </summary>
        public static string Startup_FlipViewItem1_Content_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem1_Content_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIENS UTILES.
        /// </summary>
        public static string Startup_FlipViewItem1_Title_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem1_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mains en l&apos;air ! Tout vos
        ///rendez-vous affichés ici....
        /// </summary>
        public static string Startup_FlipViewItem2_Content_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem2_Content_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENDEZ-VOUS.
        /// </summary>
        public static string Startup_FlipViewItem2_Title_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem2_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les documents à connaître
        ///sont ici....
        /// </summary>
        public static string Startup_FlipViewItem3_Content_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem3_Content_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCUMENTS.
        /// </summary>
        public static string Startup_FlipViewItem3_Title_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem3_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ici une super feature qui n&apos;attends que vous..
        /// </summary>
        public static string Startup_FlipViewItem4_Content_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem4_Content_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURE CACHÉE.
        /// </summary>
        public static string Startup_FlipViewItem4_Title_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem4_Title_Text", resourceCulture);
            }
        }
    }
}
