// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MyCompanyInThePocket.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringValues {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringValues() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MyCompanyInThePocket.Core.Resources.StringValues", typeof(StringValues).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Startup_FlipViewItem1_Content_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem1_Content_Text", resourceCulture);
            }
        }
        
        public static string Startup_FlipViewItem1_Title_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem1_Title_Text", resourceCulture);
            }
        }
        
        public static string Startup_FlipViewItem2_Content_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem2_Content_Text", resourceCulture);
            }
        }
        
        public static string Startup_FlipViewItem2_Title_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem2_Title_Text", resourceCulture);
            }
        }
        
        public static string Startup_FlipViewItem3_Content_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem3_Content_Text", resourceCulture);
            }
        }
        
        public static string Startup_FlipViewItem3_Title_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem3_Title_Text", resourceCulture);
            }
        }
        
        public static string Startup_FlipViewItem4_Content_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem4_Content_Text", resourceCulture);
            }
        }
        
        public static string Startup_FlipViewItem4_Title_Text {
            get {
                return ResourceManager.GetString("Startup_FlipViewItem4_Title_Text", resourceCulture);
            }
        }
        
        public static string Main_Meetings_Title_Text {
            get {
                return ResourceManager.GetString("Main_Meetings_Title_Text", resourceCulture);
            }
        }
        
        public static string Main_Settings_Title_Text {
            get {
                return ResourceManager.GetString("Main_Settings_Title_Text", resourceCulture);
            }
        }
        
        public static string Main_Settings_Logout {
            get {
                return ResourceManager.GetString("Main_Settings_Logout", resourceCulture);
            }
        }
        
        public static string Main_UseFullLinks_Title_Text {
            get {
                return ResourceManager.GetString("Main_UseFullLinks_Title_Text", resourceCulture);
            }
        }
        
        public static string MeetingType_AvantVente {
            get {
                return ResourceManager.GetString("MeetingType_AvantVente", resourceCulture);
            }
        }
        
        public static string MeetingType_Mission {
            get {
                return ResourceManager.GetString("MeetingType_Mission", resourceCulture);
            }
        }
        
        public static string MeetingType_Conference {
            get {
                return ResourceManager.GetString("MeetingType_Conference", resourceCulture);
            }
        }
        
        public static string MeetingType_CP_RTT {
            get {
                return ResourceManager.GetString("MeetingType_CP_RTT", resourceCulture);
            }
        }
        
        public static string MeetingType_NonFacture {
            get {
                return ResourceManager.GetString("MeetingType_NonFacture", resourceCulture);
            }
        }
    }
}
